version: '3'

services:
  php:
    container_name: php
    image: laric/php-fpm
    links:
      - postgres
    volumes:
      - ./app:/app
    tty: true

  postgres:
    container_name: postgres
    image: postgres:11-alpine
    ports:
      - 5400:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: aeoikj_9217

  nginx:
    container_name: nginx
    image: nginx:1.13.9-alpine
    links:
      - php
    ports:
      - 9000:8000
    volumes:
      - ./app:/app
      - ./nginx/services:/etc/nginx/conf.d
    tty: true
